### ISSUE TITLE
When you try to reach the /applications route it will return an error and the page won't render. Keycloak version > ~26.2.x

### ISSUE THREAD

**Issue by Gombally** [p2-inc/keycloak-account-v1#15]
It seems to work with Keycloak version 26.1, but when we try with latest 26.2.3 (moment of verifying) that specific page will just break and receives an error.

For context I'm talking about this route:

/realms/myrealm/account/applications

```
2025-05-06 10:41:07,126 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-3) Uncaught server error: java.lang.NoSuchMethodError: 'org.keycloak.services.resources.admin.permissions.RealmsPermissionEvaluator org.keycloak.services.resources.admin.permissions.AdminPermissions.realms(org.keycloak.models.KeycloakSession, org.keycloak.models.RealmModel, org.keycloak.models.UserModel)'
    at org.keycloa...
```

**Comment by xgp** [comment]
@Gombally Thanks for the report. This hasn't been ported to `26`. We'll look at it as soon as we can, but feel free to PR in the meantime.
